<?php 
function your_prefix_get_meta_box( $meta_boxes ) {
  $prefix = 'meta-';

  $meta_boxes[] = array(
    'id' => 'hotels-info',
    'title' => esc_html__( 'Информация', 'hotels-info' ),
    'post_types' => array( 'hotels' ),
    'context' => 'advanced',
    'priority' => 'default',
    'autosave' => true,
    'fields' => array(
      array(
        'name'  => 'Все фотографии',
        'id' => $prefix . 'hotel-all-photos',
        'type' => 'image_advanced',
      ),
      array(
        'name'  => 'Все контакты',
        'id' => $prefix . 'hotel-all-contacts',
        'type' => 'wysiwyg',
        'options' => array(
          'textarea_rows' => 4,
        ),
      ),
      array(
        'name'  => 'Фотографии территории',
        'id' => $prefix . 'hotel-photos',
        'type' => 'image_advanced',
      ),
      array(
        'name'  => 'Рейтинг (Главный)',
        'id' => $prefix . 'hotel-mainrating',
        'type' => 'number',
        'std'  => 1,
      ),
      array(
        'name'  => 'Кол-во оценок',
        'id' => $prefix . 'hotel-rating-count',
        'type' => 'number',
        'std'  => 1,
      ),
      array(
        'name'  => 'Минимальная стоимость',
        'id' => $prefix . 'hotel-minprice',
        'type' => 'number',
        'std'  => 1,
      ),
      array(
        'name'  => 'Максимальная стоимость',
        'id' => $prefix . 'hotel-maxprice',
        'type' => 'number',
        'std'  => 2,
      ),
      array(
        'name'  => 'Открыть отзывы?',
        'id' => $prefix . 'hotel-reviews',
        'type' => 'checkbox',
        'std'  => 0,
      ),
    ),
  );

  $meta_boxes[] = array(
    'id' => 'hotels-contact',
    'title' => esc_html__( 'Контакты', 'hotels-contact' ),
    'post_types' => array( 'hotels' ),
    'context' => 'advanced',
    'priority' => 'default',
    'autosave' => true,
    'fields' => array(
      array(
        'id' => $prefix . 'hotel-address',
        'type' => 'text',
        'name' => esc_html__( 'Адрес', 'hotels-contact' ),
      ),
      array(
        'id'            => $prefix . 'hotel-map',
        'name'          => 'Location',
        'type'          => 'map',

        // Default location: 'latitude,longitude[,zoom]' (zoom is optional)
        'std'           => '-6.233406,-35.049906,15',

        // Address field ID
        'address_field' => $prefix . 'hotel-address',

        // Google API key
        'api_key'       => 'AIzaSyA7ofGxkOMREhswh27U_aOa-eLyzBfyZkI',
      ),
      array(
        'id' => $prefix . 'hotel-gps',
        'type' => 'text',
        'name' => esc_html__( 'GPS', 'hotels-contact' ),
      ),
      array(
        'name'  => 'Телефоны',
        'id'    => $prefix . 'hotel-phones',
        'size'        => 50,
        'field_type' => 'text',
        'clone' => true,
      ),
      array(
        'name'  => 'Viber',
        'id'    => $prefix . 'hotel-viber',
        'size'        => 50,
        'field_type' => 'text',
        'clone' => true,
      ),
      array(
        'name'  => 'Whatsapp',
        'id'    => $prefix . 'hotel-whatsapp',
        'size'        => 50,
        'field_type' => 'text',
        'clone' => true,
      ),
      array(
        'name'  => 'Telegram',
        'id'    => $prefix . 'hotel-telegram',
        'size'        => 50,
        'field_type' => 'text',
        'clone' => true,
      ),
    ),
  );

  $meta_boxes[] = array(
    'id' => 'hotels-sale',
    'title' => esc_html__( 'Скидки', 'hotels-sale' ),
    'post_types' => array( 'hotels' ),
    'context' => 'advanced',
    'priority' => 'default',
    'autosave' => true,
    'fields' => array(
      array(
        'name'  => 'Есть скидки?',
        'id' => $prefix . 'hotel-sale',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Текст',
        'id' => $prefix . 'hotel-sale-text',
        'type' => 'wysiwyg',
        'options' => array(
          'textarea_rows' => 4,
        ),
      ),
    ),
  );

  $meta_boxes[] = array(
    'id' => 'hotels-include',
    'title' => esc_html__( 'Удобства', 'hotels-include' ),
    'post_types' => array( 'hotels' ),
    'context' => 'advanced',
    'priority' => 'default',
    'autosave' => true,
    'fields' => array(
      array(
        'name'  => 'Парковка',
        'id' => $prefix . 'hotel-parking',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Детская площадка',
        'id' => $prefix . 'hotel-playground',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Бассейн',
        'id' => $prefix . 'hotel-pool',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Трансфер',
        'id' => $prefix . 'hotel-transfer',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Зона отдыха',
        'id' => $prefix . 'hotel-restzone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кухня',
        'id' => $prefix . 'hotel-kitchen',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Стиральная машина',
        'id' => $prefix . 'hotel-stiralka',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Бильярд',
        'id' => $prefix . 'hotel-billiard',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Спортивная площадка',
        'id' => $prefix . 'hotel-workout',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Сауна',
        'id' => $prefix . 'hotel-sauna',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Камера хранения',
        'id' => $prefix . 'hotel-lockers',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Безналичный расчет',
        'id' => $prefix . 'hotel-mastercard',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Рядом рынок/супермаркет',
        'id' => $prefix . 'hotel-market',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Частный пляж',
        'id' => $prefix . 'hotel-beach',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Аренда лежаков',
        'id' => $prefix . 'hotel-lejak',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кафе/ресторан',
        'id' => $prefix . 'hotel-restrant',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Мангал',
        'id' => $prefix . 'hotel-mangal',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Аренда лыжного снаряжения',
        'id' => $prefix . 'hotel-arendaski',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Доставка продуктов',
        'id' => $prefix . 'hotel-deliveryfoods',
        'type' => 'checkbox',
        'std'  => 0,
      ),
    ),
  );

  $meta_boxes[] = array(
    'id' => 'hotels-kottedg',
    'title' => esc_html__( 'Коттедж', 'hotels-kottedg' ),
    'post_types' => array( 'hotels' ),
    'context' => 'advanced',
    'priority' => 'default',
    'autosave' => true,
    'fields' => array(
      array(
        'name'  => 'Есть такие?',
        'id' => $prefix . 'hotel-kottedg-has',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фотографии коттеджных номеров',
        'id' => $prefix . 'hotel-kottedg-photos',
        'type' => 'image_advanced',
      ),
      array(
        'name'  => 'Минимальная стоимость в сезон',
        'id' => $prefix . 'hotel-kottedg-minprice_sezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Максимальная стоимость в сезон',
        'id' => $prefix . 'hotel-kottedg-maxprice_sezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Минимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-kottedg-minprice_nesezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Максимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-kottedg-maxprice_nesezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Кол-во мест',
        'id'    => $prefix . 'hotel-kottedg-nomers-qty',
        'size'        => 50,
        'field_type' => 'text',
      ),
      array(
        'name'  => 'Одноместные',
        'id' => $prefix . 'hotel-kottedg-hasone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Двуместные',
        'id' => $prefix . 'hotel-kottedg-hastwo',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Трехместные',
        'id' => $prefix . 'hotel-kottedg-hasthree',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Четырехместные',
        'id' => $prefix . 'hotel-kottedg-hasfour',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Пятиместные',
        'id' => $prefix . 'hotel-kottedg-hasfive',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Шестиместные',
        'id' => $prefix . 'hotel-kottedg-hassix',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Семиместные',
        'id' => $prefix . 'hotel-kottedg-hasseven',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кондиционер',
        'id' => $prefix . 'hotel-kottedg-conder',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телевизор',
        'id' => $prefix . 'hotel-kottedg-tv',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Холодильник',
        'id' => $prefix . 'hotel-kottedg-frize',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Чайник',
        'id' => $prefix . 'hotel-kottedg-boiling',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Аптечка',
        'id' => $prefix . 'hotel-kottedg-aptechka',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фен',
        'id' => $prefix . 'hotel-kottedg-fen',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Микроволновая печь',
        'id' => $prefix . 'hotel-kottedg-micro',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кофеварка',
        'id' => $prefix . 'hotel-kottedg-coffee',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Утюг',
        'id' => $prefix . 'hotel-kottedg-utug',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Санузел',
        'id' => $prefix . 'hotel-kottedg-sanuzel',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Душ',
        'id' => $prefix . 'hotel-kottedg-dush',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Сейф',
        'id' => $prefix . 'hotel-kottedg-safe',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вентилятор',
        'id' => $prefix . 'hotel-kottedg-fan',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Уборка в номере',
        'id' => $prefix . 'hotel-kottedg-clean',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Wi-Fi',
        'id' => $prefix . 'hotel-kottedg-wifi',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на море',
        'id' => $prefix . 'hotel-kottedg-sunset',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Минибар',
        'id' => $prefix . 'hotel-kottedg-minibar',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телефон',
        'id' => $prefix . 'hotel-kottedg-telephone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на горы',
        'id' => $prefix . 'hotel-kottedg-mountview',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Камин',
        'id' => $prefix . 'hotel-kottedg-kamin',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Спутниковое ТВ',
        'id' => $prefix . 'hotel-kottedg-sputnik',
        'type' => 'checkbox',
        'std'  => 0,
      ),
    ),
  );

  $meta_boxes[] = array(
    'id' => 'hotels-lux',
    'title' => esc_html__( 'Номера люкс', 'hotels-lux' ),
    'post_types' => array( 'hotels' ),
    'context' => 'advanced',
    'priority' => 'default',
    'autosave' => true,
    'fields' => array(
      array(
        'name'  => 'Есть такие?',
        'id' => $prefix . 'hotel-lux-has',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фотографии люксовых номеров',
        'id' => $prefix . 'hotel-lux-photos',
        'type' => 'image_advanced',
      ),
      array(
        'name'  => 'Минимальная стоимость в сезон',
        'id' => $prefix . 'hotel-lux-minprice_sezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Максимальная стоимость в сезон',
        'id' => $prefix . 'hotel-lux-maxprice_sezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Минимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-lux-minprice_nesezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Максимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-lux-maxprice_nesezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Кол-во мест',
        'id'    => $prefix . 'hotel-lux-nomers-qty',
        'size'        => 50,
        'field_type' => 'text',
      ),
      array(
        'name'  => 'Одноместные',
        'id' => $prefix . 'hotel-lux-hasone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Двуместные',
        'id' => $prefix . 'hotel-lux-hastwo',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Трехместные',
        'id' => $prefix . 'hotel-lux-hasthree',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Четырехместные',
        'id' => $prefix . 'hotel-lux-hasfour',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Пятиместные',
        'id' => $prefix . 'hotel-lux-hasfive',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Шестиместные',
        'id' => $prefix . 'hotel-lux-hassix',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Семиместные',
        'id' => $prefix . 'hotel-lux-hasseven',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кондиционер',
        'id' => $prefix . 'hotel-lux-conder',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телевизор',
        'id' => $prefix . 'hotel-lux-tv',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Холодильник',
        'id' => $prefix . 'hotel-lux-frize',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Чайник',
        'id' => $prefix . 'hotel-lux-boiling',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Аптечка',
        'id' => $prefix . 'hotel-lux-aptechka',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фен',
        'id' => $prefix . 'hotel-lux-fen',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Микроволновая печь',
        'id' => $prefix . 'hotel-lux-micro',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кофеварка',
        'id' => $prefix . 'hotel-lux-coffee',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Утюг',
        'id' => $prefix . 'hotel-lux-utug',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Санузел',
        'id' => $prefix . 'hotel-lux-sanuzel',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Душ',
        'id' => $prefix . 'hotel-lux-dush',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Сейф',
        'id' => $prefix . 'hotel-lux-safe',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вентилятор',
        'id' => $prefix . 'hotel-lux-fan',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Уборка в номере',
        'id' => $prefix . 'hotel-lux-clean',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Wi-Fi',
        'id' => $prefix . 'hotel-lux-wifi',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на море',
        'id' => $prefix . 'hotel-lux-sunset',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Минибар',
        'id' => $prefix . 'hotel-lux-minibar',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телефон',
        'id' => $prefix . 'hotel-lux-telephone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на горы',
        'id' => $prefix . 'hotel-lux-mountview',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Камин',
        'id' => $prefix . 'hotel-lux-kamin',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Спутниковое ТВ',
        'id' => $prefix . 'hotel-lux-sputnik',
        'type' => 'checkbox',
        'std'  => 0,
      ),
    ),
  );

  $meta_boxes[] = array(
    'id' => 'hotels-halflux',
    'title' => esc_html__( 'Номера полулюкс', 'hotels-halflux' ),
    'post_types' => array( 'hotels' ),
    'context' => 'advanced',
    'priority' => 'default',
    'autosave' => true,
    'fields' => array(
      array(
        'name'  => 'Есть такие?',
        'id' => $prefix . 'hotel-halflux-has',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фотографии полулюксовых номеров',
        'id' => $prefix . 'hotel-halflux-photos',
        'type' => 'image_advanced',
      ),
      array(
        'name'  => 'Минимальная стоимость в сезон',
        'id' => $prefix . 'hotel-halflux-minprice_sezon',
        'type' => 'number',
      ),
       array(
        'name'  => 'Максимальная стоимость в сезон',
        'id' => $prefix . 'hotel-halflux-maxprice_sezon',
        'type' => 'number',
      ),
        array(
        'name'  => 'Минимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-halflux-minprice_nesezon',
        'type' => 'number',
      ),
         array(
        'name'  => 'Максимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-halflux-maxprice_nesezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Кол-во мест',
        'id'    => $prefix . 'hotel-halflux-nomers-qty',
        'size'        => 50,
        'field_type' => 'text',
      ),
      array(
        'name'  => 'Одноместные',
        'id' => $prefix . 'hotel-halflux-hasone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Двуместные',
        'id' => $prefix . 'hotel-halflux-hastwo',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Трехместные',
        'id' => $prefix . 'hotel-halflux-hasthree',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Четырехместные',
        'id' => $prefix . 'hotel-halflux-hasfour',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Пятиместные',
        'id' => $prefix . 'hotel-halflux-hasfive',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Шестиместные',
        'id' => $prefix . 'hotel-halflux-hassix',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Семиместные',
        'id' => $prefix . 'hotel-halflux-hasseven',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кондиционер',
        'id' => $prefix . 'hotel-halflux-conder',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телевизор',
        'id' => $prefix . 'hotel-halflux-tv',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Холодильник',
        'id' => $prefix . 'hotel-halflux-frize',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Чайник',
        'id' => $prefix . 'hotel-halflux-boiling',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Аптечка',
        'id' => $prefix . 'hotel-halflux-aptechka',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фен',
        'id' => $prefix . 'hotel-halflux-fen',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Микроволновая печь',
        'id' => $prefix . 'hotel-halflux-micro',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кофеварка',
        'id' => $prefix . 'hotel-halflux-coffee',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Утюг',
        'id' => $prefix . 'hotel-halflux-utug',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Санузел',
        'id' => $prefix . 'hotel-halflux-sanuzel',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Душ',
        'id' => $prefix . 'hotel-halflux-dush',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Сейф',
        'id' => $prefix . 'hotel-halflux-safe',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вентилятор',
        'id' => $prefix . 'hotel-halflux-fan',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Уборка в номере',
        'id' => $prefix . 'hotel-halflux-clean',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Wi-Fi',
        'id' => $prefix . 'hotel-halflux-wifi',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на море',
        'id' => $prefix . 'hotel-halflux-sunset',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Минибар',
        'id' => $prefix . 'hotel-halflux-minibar',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телефон',
        'id' => $prefix . 'hotel-halflux-telephone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на горы',
        'id' => $prefix . 'hotel-halflux-mountview',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Камин',
        'id' => $prefix . 'hotel-halflux-kamin',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Спутниковое ТВ',
        'id' => $prefix . 'hotel-halflux-sputnik',
        'type' => 'checkbox',
        'std'  => 0,
      ),
    ),
  );

  $meta_boxes[] = array(
    'id' => 'hotels-standart',
    'title' => esc_html__( 'Номера Стандарт', 'hotels-standart' ),
    'post_types' => array( 'hotels' ),
    'context' => 'advanced',
    'priority' => 'default',
    'autosave' => true,
    'fields' => array(
      array(
        'name'  => 'Есть такие?',
        'id' => $prefix . 'hotel-standart-has',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фотографии стандартных номеров',
        'id' => $prefix . 'hotel-standart-photos',
        'type' => 'image_advanced',
      ),
      array(
        'name'  => 'Минимальная стоимость в сезон',
        'id' => $prefix . 'hotel-standart-minprice_sezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Максимальная стоимость в сезон',
        'id' => $prefix . 'hotel-standart-maxprice_sezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Минимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-standart-minprice_nesezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Максимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-standart-maxprice_nesezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Кол-во мест',
        'id'    => $prefix . 'hotel-standart-nomers-qty',
        'size'        => 50,
        'field_type' => 'text',
      ),
      array(
        'name'  => 'Одноместные',
        'id' => $prefix . 'hotel-standart-hasone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Двуместные',
        'id' => $prefix . 'hotel-standart-hastwo',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Трехместные',
        'id' => $prefix . 'hotel-standart-hasthree',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Четырехместные',
        'id' => $prefix . 'hotel-standart-hasfour',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Пятиместные',
        'id' => $prefix . 'hotel-standart-hasfive',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Шестиместные',
        'id' => $prefix . 'hotel-standart-hassix',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Семиместные',
        'id' => $prefix . 'hotel-standart-hasseven',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кондиционер',
        'id' => $prefix . 'hotel-standart-conder',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телевизор',
        'id' => $prefix . 'hotel-standart-tv',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Холодильник',
        'id' => $prefix . 'hotel-standart-frize',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Чайник',
        'id' => $prefix . 'hotel-standart-boiling',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Аптечка',
        'id' => $prefix . 'hotel-standart-aptechka',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фен',
        'id' => $prefix . 'hotel-standart-fen',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Микроволновая печь',
        'id' => $prefix . 'hotel-standart-micro',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кофеварка',
        'id' => $prefix . 'hotel-standart-coffee',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Утюг',
        'id' => $prefix . 'hotel-standart-utug',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Санузел',
        'id' => $prefix . 'hotel-standart-sanuzel',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Душ',
        'id' => $prefix . 'hotel-standart-dush',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Сейф',
        'id' => $prefix . 'hotel-standart-safe',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вентилятор',
        'id' => $prefix . 'hotel-standart-fan',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Уборка в номере',
        'id' => $prefix . 'hotel-standart-clean',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Wi-Fi',
        'id' => $prefix . 'hotel-standart-wifi',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на море',
        'id' => $prefix . 'hotel-standart-sunset',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Минибар',
        'id' => $prefix . 'hotel-standart-minibar',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телефон',
        'id' => $prefix . 'hotel-standart-telephone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на горы',
        'id' => $prefix . 'hotel-standart-mountview',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Камин',
        'id' => $prefix . 'hotel-standart-kamin',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Спутниковое ТВ',
        'id' => $prefix . 'hotel-standart-sputnik',
        'type' => 'checkbox',
        'std'  => 0,
      ),
    ),
  );

  $meta_boxes[] = array(
    'id' => 'hotels-budget',
    'title' => esc_html__( 'Бюджетные номера', 'hotels-budget' ),
    'post_types' => array( 'hotels' ),
    'context' => 'advanced',
    'priority' => 'default',
    'autosave' => true,
    'fields' => array(
      array(
        'name'  => 'Есть такие?',
        'id' => $prefix . 'hotel-budget-has',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фотографии бюджетных номеров',
        'id' => $prefix . 'hotel-budget-photos',
        'type' => 'image_advanced',
      ),
      array(
        'name'  => 'Минимальная стоимость в сезон',
        'id' => $prefix . 'hotel-budget-minprice_sezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Максимальная стоимость в сезон',
        'id' => $prefix . 'hotel-budget-maxprice_sezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Минимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-budget-minprice_nesezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Максимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-budget-maxprice_nesezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Кол-во мест',
        'id'    => $prefix . 'hotel-budget-nomers-qty',
        'size'        => 50,
        'field_type' => 'text',
      ),
      array(
        'name'  => 'Одноместные',
        'id' => $prefix . 'hotel-budget-hasone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Двуместные',
        'id' => $prefix . 'hotel-budget-hastwo',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Трехместные',
        'id' => $prefix . 'hotel-budget-hasthree',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Четырехместные',
        'id' => $prefix . 'hotel-budget-hasfour',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Пятиместные',
        'id' => $prefix . 'hotel-budget-hasfive',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Шестиместные',
        'id' => $prefix . 'hotel-budget-hassix',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Семиместные',
        'id' => $prefix . 'hotel-budget-hasseven',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кондиционер',
        'id' => $prefix . 'hotel-budget-conder',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телевизор',
        'id' => $prefix . 'hotel-budget-tv',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Холодильник',
        'id' => $prefix . 'hotel-budget-frize',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Чайник',
        'id' => $prefix . 'hotel-budget-boiling',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Аптечка',
        'id' => $prefix . 'hotel-budget-aptechka',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фен',
        'id' => $prefix . 'hotel-budget-fen',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Микроволновая печь',
        'id' => $prefix . 'hotel-budget-micro',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кофеварка',
        'id' => $prefix . 'hotel-budget-coffee',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Утюг',
        'id' => $prefix . 'hotel-budget-utug',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Санузел',
        'id' => $prefix . 'hotel-budget-sanuzel',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Душ',
        'id' => $prefix . 'hotel-budget-dush',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Сейф',
        'id' => $prefix . 'hotel-budget-safe',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вентилятор',
        'id' => $prefix . 'hotel-budget-fan',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Уборка в номере',
        'id' => $prefix . 'hotel-budget-clean',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Wi-Fi',
        'id' => $prefix . 'hotel-budget-wifi',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на море',
        'id' => $prefix . 'hotel-budget-sunset',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Минибар',
        'id' => $prefix . 'hotel-budget-minibar',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телефон',
        'id' => $prefix . 'hotel-budget-telephone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на горы',
        'id' => $prefix . 'hotel-budget-mountview',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Камин',
        'id' => $prefix . 'hotel-budget-kamin',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Спутниковое ТВ',
        'id' => $prefix . 'hotel-budget-sputnik',
        'type' => 'checkbox',
        'std'  => 0,
      ),
    ),
  );

  $meta_boxes[] = array(
    'id' => 'hotels-appartment',
    'title' => esc_html__( 'Квартира', 'hotels-appartment' ),
    'post_types' => array( 'hotels' ),
    'context' => 'advanced',
    'priority' => 'default',
    'autosave' => true,
    'fields' => array(
      array(
        'name'  => 'Есть такие?',
        'id' => $prefix . 'hotel-appartment-has',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фотографии квартиры',
        'id' => $prefix . 'hotel-appartment-photos',
        'type' => 'image_advanced',
      ),
      array(
        'name'  => 'Минимальная стоимость в сезон',
        'id' => $prefix . 'hotel-appartment-minprice_sezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Максимальная стоимость в сезон',
        'id' => $prefix . 'hotel-appartment-maxprice_sezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Минимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-appartment-minprice_nesezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Максимальная стоимость в не сезон',
        'id' => $prefix . 'hotel-appartment-maxprice_nesezon',
        'type' => 'number',
      ),
      array(
        'name'  => 'Кол-во мест',
        'id'    => $prefix . 'hotel-appartment-nomers-qty',
        'size'        => 50,
        'field_type' => 'text',
      ),
      array(
        'name'  => 'Одноместные',
        'id' => $prefix . 'hotel-appartment-hasone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Двуместные',
        'id' => $prefix . 'hotel-appartment-hastwo',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Трехместные',
        'id' => $prefix . 'hotel-appartment-hasthree',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Четырехместные',
        'id' => $prefix . 'hotel-appartment-hasfour',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Пятиместные',
        'id' => $prefix . 'hotel-appartment-hasfive',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Шестиместные',
        'id' => $prefix . 'hotel-appartment-hassix',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Семиместные',
        'id' => $prefix . 'hotel-appartment-hasseven',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кондиционер',
        'id' => $prefix . 'hotel-appartment-conder',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телевизор',
        'id' => $prefix . 'hotel-appartment-tv',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Холодильник',
        'id' => $prefix . 'hotel-appartment-frize',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Чайник',
        'id' => $prefix . 'hotel-appartment-boiling',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Аптечка',
        'id' => $prefix . 'hotel-appartment-aptechka',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Фен',
        'id' => $prefix . 'hotel-appartment-fen',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Микроволновая печь',
        'id' => $prefix . 'hotel-appartment-micro',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Кофеварка',
        'id' => $prefix . 'hotel-appartment-coffee',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Утюг',
        'id' => $prefix . 'hotel-appartment-utug',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Санузел',
        'id' => $prefix . 'hotel-appartment-sanuzel',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Душ',
        'id' => $prefix . 'hotel-appartment-dush',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Сейф',
        'id' => $prefix . 'hotel-appartment-safe',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вентилятор',
        'id' => $prefix . 'hotel-appartment-fan',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Уборка в номере',
        'id' => $prefix . 'hotel-appartment-clean',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Wi-Fi',
        'id' => $prefix . 'hotel-appartment-wifi',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на море',
        'id' => $prefix . 'hotel-appartment-sunset',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Минибар',
        'id' => $prefix . 'hotel-appartment-minibar',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Телефон',
        'id' => $prefix . 'hotel-appartment-telephone',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Вид на горы',
        'id' => $prefix . 'hotel-appartment-mountview',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Камин',
        'id' => $prefix . 'hotel-appartment-kamin',
        'type' => 'checkbox',
        'std'  => 0,
      ),
      array(
        'name'  => 'Спутниковое ТВ',
        'id' => $prefix . 'hotel-appartment-sputnik',
        'type' => 'checkbox',
        'std'  => 0,
      ),
    ),
  );

  $meta_boxes[] = array(
    'id' => 'youtube-video',
    'title' => 'Видео',
    'post_types' => array( 'youtube' ),
    'context' => 'advanced',
    'priority' => 'default',
    'autosave' => true,
    'fields' => array(
      array(
        'name'  => 'Id',
        'id' => $prefix . 'youtube-id',
        'type' => 'text',
      ),
    ),
  );

  return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'your_prefix_get_meta_box' );

?>